### PR TITLE
New approach for consideration

### PR DESCRIPTION
**Pull request by dahlsailrunner**
I think this would in general leave things alone for anyone already using it, but enable folks to use it out of the box in a clean way when they have custom needs.  The sample app shows how you'd use it to do custom logging -- without including the stuff from the original log entries.

And if the caller doesn't provide a custom function then it would behave as it had before - logging a full HttpContextCache object.

I've been thinking about this and it would seem like flags to include this, exclude that, but only when X -- it would be hard to anticipate all of the real needs from different applications.  And so use the out-of-the-box approach when they have simple needs, and just a simple custom function when they want to specify their own stuff.  

Thoughts?

### CODE REVIEW

**Comment by dahlsailrunner** [comment]
PS - I can add some documentation to the readme if this seems like a reasonable approach.

**Comment by trenoncourt** [comment]
Hi @dahlsailrunner,

I agree with your proposal.
For the flags, we can add them step by step and by need.

Thanks for you contribution.

**Comment by dahlsailrunner** [comment]
Done.  Have a look at the edits I made to the readme and let me know what you think.  Sorry for the delay.  Had the whole "Thanksgiving holiday" thing going on.  :)

**Comment by trenoncourt** [comment]
hi @dahlsailrunner, thanks for the update, yes lot of work during last weeks ;)

**Pull request merged**
